image: ruby:3.0

variables:
  DEBIAN_FRONTEND: noninteractive
  LANG: en_US.UTF-8
  LANGUAGE: en_US:en
  LC_ALL: en_US.UTF-8
  JEKYLL_ENV: production

before_script:
  - apt-get update
  - apt-get install -y locales
  - echo "${LANG} UTF-8" > /etc/locale.gen
  - locale-gen ${LANG}
  - bundle install

site-build:
  stage: build
  script:
    - cd test-website
    - bundle exec jekyll build

